name: Release

on:
  create

defaults:
  run:
    shell: pwsh
    
env:
  DOTNET_VERSION: 10.0.302
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget
  
jobs:
  publish_package:
    if: ${{ contains(github.ref, 'refs/heads/releases/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v7
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
          ${{ env.DOTNET_VERSION }}      
          
    - name: Define global.json
      run: dotnet new globaljson --sdk-version ${{ env.DOTNET_VERSION }}    

    - name: Create nuget package
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}

    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: kiyote

    - name: Publish NuGet package
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
        }        
